config/routes.rb
Rails.application.routes.draw do

   root to: 'application#index'

   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)



   devise_for :users

   resources :users do
      collection do
         get 'show_staff' => 'users#show_staff'
      end
   end

   resources :treatment_plan_notes
   resources :intake_notes
   resources :progress_notes
   resources :to_do_lists
   resources :general_informations
   resources :health_insurances
   resources :family_histories
   resources :emergency_contacts
   resources :immunizations
   resources :diagnoses



   resources :patients

   resources :medications

   resources :allergies


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/allergy.rb
class Allergy < ApplicationRecord
   belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
   belongs_to :patient
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
   belongs_to :patient
end

app/models/family_history.rb
class FamilyHistory < ApplicationRecord
  belongs_to :patient
end

app/models/health_insurance.rb
class HealthInsurance < ApplicationRecord
  belongs_to :patient
end

app/models/immunization.rb
class Immunization < ApplicationRecord
  belongs_to :patient
end

app/models/intake_note.rb
class IntakeNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/medication.rb
class Medication < ApplicationRecord
   belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
   belongs_to :user
   has_one :medication
   has_one :allergy
   has_one :general_information
   has_one :immunization
   has_one :health_insurance
   has_one :family_history
   has_one :emergency_contact
   has_one :diagnosis
   has_many :progress_notes
   has_many :intake_notes
   has_many :treatment_plan_notes

   validates :first_name, presence: true
end

app/models/progress_note.rb
class ProgressNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
   has_many :patients
   has_many :to_do_lists

      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

end

app/controllers/progress_notes_controller.rb
class ProgressNotesController < ApplicationController
  before_action :set_progress_note, only: [:show, :edit, :update, :destroy]

  # GET /progress_notes
  # GET /progress_notes.json
  def index
    @progress_notes = ProgressNote.all
  end

  # GET /progress_notes/1
  # GET /progress_notes/1.json
  def show
  end

   # GET /progress_notes/new
   def new
      @users=User.all
      @patients=Patient.all
      @progress_note = ProgressNote.new
   end

   # GET /progress_notes/1/edit
   def edit
      @users=User.all
      @patients=Patient.all
   end

  # POST /progress_notes
  # POST /progress_notes.json
  def create
    @progress_note = ProgressNote.new(progress_note_params)

    respond_to do |format|
      if @progress_note.save
        format.html { redirect_to patient_path(@progress_note.patient), notice: 'Progress note was successfully created.' }
        format.json { render :show, status: :created, location: @progress_note }
      else
        format.html { render :new }
        format.json { render json: @progress_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progress_notes/1
  # PATCH/PUT /progress_notes/1.json
  def update
    respond_to do |format|
      if @progress_note.update(progress_note_params)
        format.html { redirect_to patient_path(@progress_note.patient), notice: 'Progress note was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress_note }
      else
        format.html { render :edit }
        format.json { render json: @progress_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progress_notes/1
  # DELETE /progress_notes/1.json
  def destroy
    @progress_note.destroy
    respond_to do |format|
      format.html { redirect_to progress_notes_url, notice: 'Progress note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress_note
      @progress_note = ProgressNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_note_params
      params.require(:progress_note).permit(:user_id, :patient_id, :date, :time, :duration, :location, :mental_status, :symptoms, :dx, :prognosis, :progress_to_date, :tx_plan, :progress_note, :note_type)
    end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/progress_notes_helper.rb
module ProgressNotesHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/progress_notes/_form.html.erb
<%= form_with(model: progress_note, local: true) do |form| %>
  <% if progress_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(progress_note.errors.count, "error") %> prohibited this progress_note from being saved:</h2>

      <ul>
      <% progress_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="row">
     <div class="col-md-6">


        <div class="form-group">
          <%= form.label :mental_status %>
          <%= form.text_field :mental_status, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :symptoms %>
          <%= form.text_area :symptoms, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :dx %>
          <%= form.text_field :dx , class:'form-control'%>
        </div>

        <div class="form-group">
          <%= form.label :prognosis %>
          <%= form.text_field :prognosis, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :progress_to_date %>
          <%= form.text_field :progress_to_date, class:'form-control' %>
        </div>

        <div class="form-group">
        <%= form.label :tx_plan %>
        <%= form.text_field :tx_plan, class:'form-control' %>
      </div>


     </div>

     <div class="col-md-6">

        <div class="form-group">
          <%= form.label :note_type %>
          <%= form.text_field :note_type, class:'form-control'%>
        </div>

        <div class="form-group">
          <%= form.label :location %>
          <%= form.text_field :location, class:'form-control' %>
        </div>


        <div class="form-group">
          <%= form.label :patient_id %>
          <%= form.select('patient_id', options_for_select(@patients.collect{ |p| [ p.first_name, p.id ] }), class:'form-control') %>
        </div>

        <div class="form-group">
          <%= form.label :user_id %>
          <%= form.select('user_id', options_for_select(@users.collect{ |p| [ p.first_name, p.id ] }), class:'form-control') %>
        </div>

        <div class="form-group">
          <%= form.label :date %>
          <%= form.date_select :date, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :time %>
          <%= form.time_select :time, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :duration %>
          <%= form.number_field :duration, class:'form-control' %>
        </div>
     </div>
   </div>

   <br>

   <div class="form-group">
     <%= form.label :progress_note %>
     <%= form.text_area :progress_note, class:'form-control' %>
   </div>

   <hr>


  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/progress_notes/edit.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>Editing Progress Note</h1>
         <%= render 'form', progress_note: @progress_note %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/progress_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Progress Notes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Patient</th>
      <th>Date</th>
      <th>Time</th>
      <th>Duration</th>
      <th>Location</th>
      <th>Mental status</th>
      <th>Symptoms</th>
      <th>Dx</th>
      <th>Prognosis</th>
      <th>Progress to date</th>
      <th>Tx plan</th>
      <th>Progress note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @progress_notes.each do |progress_note| %>
      <tr>
        <td><%= progress_note.user %></td>
        <td><%= progress_note.patient %></td>
        <td><%= progress_note.date %></td>
        <td><%= progress_note.time %></td>
        <td><%= progress_note.duration %></td>
        <td><%= progress_note.location %></td>
        <td><%= progress_note.mental_status %></td>
        <td><%= progress_note.symptoms %></td>
        <td><%= progress_note.dx %></td>
        <td><%= progress_note.prognosis %></td>
        <td><%= progress_note.progress_to_date %></td>
        <td><%= progress_note.tx_plan %></td>
        <td><%= progress_note.progress_note %></td>
        <td><%= link_to 'Show', progress_note %></td>
        <td><%= link_to 'Edit', edit_progress_note_path(progress_note) %></td>
        <td><%= link_to 'Destroy', progress_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Progress Note', new_progress_note_path %>

app/views/progress_notes/new.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>New Progress Note</h1>
         <%= render 'form', progress_note: @progress_note %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/progress_notes/show.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <div class="row">
            <div class="col-md-6">
               <h3>Patient: <small><%= @progress_note.patient.first_name %> <%= @progress_note.patient.last_name %></small></h3>
               <h3>Clinician: <small><%= @progress_note.user.first_name %> <%= @progress_note.user.last_name %></small></h3>
            </div>
            <div class="col-md-6">
               <h3>Date: <small><%= @progress_note.date %></small></h3>
            </div>
         </div>

         <hr>

         <div class="row">
            <div class="col-md-6">
               <p>
                 <strong>Time:</strong>
                 <%= @progress_note.time %>
               </p>

               <p>
                 <strong>Duration:</strong>
                 <%= @progress_note.duration %>
               </p>

               <p>
                 <strong>Location:</strong>
                 <%= @progress_note.location %>
               </p>

               <p>
                 <strong>Mental status:</strong>
                 <%= @progress_note.mental_status %>
               </p>

               <p>
                 <strong>Symptoms:</strong>
                 <%= @progress_note.symptoms %>
               </p>
            </div>
            <div class="col-md-6">
               <p>
                 <strong>Dx:</strong>
                 <%= @progress_note.dx %>
               </p>

               <p>
                 <strong>Prognosis:</strong>
                 <%= @progress_note.prognosis %>
               </p>

               <p>
                 <strong>Progress to date:</strong>
                 <%= @progress_note.progress_to_date %>
               </p>

               <p>
                 <strong>Tx plan:</strong>
                 <%= @progress_note.tx_plan %>
               </p>

            </div>
         </div>

         <div class="form-group">
            <label for="progress_note"><strong>Progress Note:</strong></label>
            <textarea class="form-control" rows="5"><%= @progress_note.progress_note %></textarea>
         </div>



         <%= link_to 'Edit', edit_progress_note_path(@progress_note) %> |
         <%= link_to 'Back', progress_notes_path %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>