config/routes.rb
Rails.application.routes.draw do

   root to: 'application#index'

   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)



   devise_for :users

   resources :users do
      collection do
         get 'show_staff' => 'users#show_staff'
      end
   end

   resources :treatment_plan_notes
   resources :intake_notes
   resources :progress_notes
   resources :to_do_lists
   resources :general_informations
   resources :health_insurances
   resources :family_histories
   resources :emergency_contacts
   resources :immunizations
   resources :diagnoses



   resources :patients

   resources :medications

   resources :allergies


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/allergy.rb
class Allergy < ApplicationRecord
   belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
   belongs_to :patient
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
   belongs_to :patient
end

app/models/family_history.rb
class FamilyHistory < ApplicationRecord
  belongs_to :patient
end

app/models/health_insurance.rb
class HealthInsurance < ApplicationRecord
  belongs_to :patient
end

app/models/immunization.rb
class Immunization < ApplicationRecord
  belongs_to :patient
end

app/models/intake_note.rb
class IntakeNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/medication.rb
class Medication < ApplicationRecord
   belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
   belongs_to :user
   has_one :medication
   has_one :allergy
   has_one :general_information
   has_one :immunization
   has_one :health_insurance
   has_one :family_history
   has_one :emergency_contact
   has_one :diagnosis
   has_many :progress_notes
   has_many :intake_notes
   has_many :treatment_plan_notes

   validates :first_name, presence: true
end

app/models/progress_note.rb
class ProgressNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
   has_many :patients
   has_many :to_do_lists

      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController
  before_action :set_emergency_contact, only: [:show, :edit, :update, :destroy]

  # GET /emergency_contacts
  # GET /emergency_contacts.json
  def index
    @emergency_contacts = EmergencyContact.all
  end

  # GET /emergency_contacts/1
  # GET /emergency_contacts/1.json
  def show
  end

   # GET /emergency_contacts/new
   def new
      @patients=Patient.all
      @emergency_contact = EmergencyContact.new
   end

   # GET /emergency_contacts/1/edit
   def edit
      @patients=Patient.all
   end

  # POST /emergency_contacts
  # POST /emergency_contacts.json
  def create
    @emergency_contact = EmergencyContact.new(emergency_contact_params)

    respond_to do |format|
      if @emergency_contact.save
        format.html { redirect_to patient_path(@emergency_contact.patient), notice: 'Emergency contact was successfully created.' }
        format.json { render :show, status: :created, location: @emergency_contact }
      else
        format.html { render :new }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergency_contacts/1
  # PATCH/PUT /emergency_contacts/1.json
  def update
    respond_to do |format|
      if @emergency_contact.update(emergency_contact_params)
        format.html { redirect_to patient_path(@emergency_contact.patient), notice: 'Emergency contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @emergency_contact }
      else
        format.html { render :edit }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergency_contacts/1
  # DELETE /emergency_contacts/1.json
  def destroy
    @emergency_contact.destroy
    respond_to do |format|
      format.html { redirect_to emergency_contacts_url, notice: 'Emergency contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency_contact
      @emergency_contact = EmergencyContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_contact_params
      params.require(:emergency_contact).permit(:first_name, :last_name, :relationship, :phone1, :phone2, :email, :address_line_1, :address_line_2, :city, :state, :zipcode, :note, :patient_id)
    end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/emergency_contacts_helper.rb
module EmergencyContactsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/emergency_contacts/_form.html.erb
<%= form_with(model: emergency_contact, local: true) do |form| %>
  <% if emergency_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emergency_contact.errors.count, "error") %> prohibited this emergency_contact from being saved:</h2>

      <ul>
      <% emergency_contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
     <div class="col-md-6">
        <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :relationship %>
          <%= form.text_field :relationship, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :phone1 %>
          <%= form.text_field :phone1, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :phone2 %>
          <%= form.text_field :phone2, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class:'form-control' %>
        </div>
     </div>
     <div class="col-md-6">
        <div class="form-group">
          <%= form.label :address_line_1 %>
          <%= form.text_field :address_line_1, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :address_line_2 %>
          <%= form.text_field :address_line_2, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :city %>
          <%= form.text_field :city, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :state %>
          <%= form.text_field :state, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :zipcode %>
          <%= form.text_field :zipcode, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :note %>
          <%= form.text_area :note, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :patient_id %>
          <%= form.select('patient_id', options_for_select(@patients.collect{ |p| [ p.first_name, p.id ] }), class:'form-control') %>
        </div>
     </div>
  </div>

  <div class="actions">
    <%= form.submit 'Update', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/emergency_contacts/edit.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>Editing Emergency Contact</h1>
         <%= render 'form', emergency_contact: @emergency_contact %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/emergency_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emergency Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Relationship</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th>Email</th>
      <th>Address line 1</th>
      <th>Address line 2</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emergency_contacts.each do |emergency_contact| %>
      <tr>
        <td><%= emergency_contact.first_name %></td>
        <td><%= emergency_contact.last_name %></td>
        <td><%= emergency_contact.relationship %></td>
        <td><%= emergency_contact.phone1 %></td>
        <td><%= emergency_contact.phone2 %></td>
        <td><%= emergency_contact.email %></td>
        <td><%= emergency_contact.address_line_1 %></td>
        <td><%= emergency_contact.address_line_2 %></td>
        <td><%= emergency_contact.city %></td>
        <td><%= emergency_contact.state %></td>
        <td><%= emergency_contact.zipcode %></td>
        <td><%= emergency_contact.note %></td>
        <td><%= link_to 'Show', emergency_contact %></td>
        <td><%= link_to 'Edit', edit_emergency_contact_path(emergency_contact) %></td>
        <td><%= link_to 'Destroy', emergency_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emergency Contact', new_emergency_contact_path %>

app/views/emergency_contacts/new.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>New Emergency Contact</h1>
         <%= render 'form', emergency_contact: @emergency_contact %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/emergency_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @emergency_contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @emergency_contact.last_name %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @emergency_contact.relationship %>
</p>

<p>
  <strong>Phone1:</strong>
  <%= @emergency_contact.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @emergency_contact.phone2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @emergency_contact.email %>
</p>

<p>
  <strong>Address line 1:</strong>
  <%= @emergency_contact.address_line_1 %>
</p>

<p>
  <strong>Address line 2:</strong>
  <%= @emergency_contact.address_line_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @emergency_contact.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @emergency_contact.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @emergency_contact.zipcode %>
</p>

<p>
  <strong>Note:</strong>
  <%= @emergency_contact.note %>
</p>

<%= link_to 'Edit', edit_emergency_contact_path(@emergency_contact) %> |
<%= link_to 'Back', emergency_contacts_path %>