config/routes.rb
Rails.application.routes.draw do

   root to: 'application#index'

   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)



   devise_for :users

   resources :users do
      collection do
         get 'show_staff' => 'users#show_staff'
      end
   end

   resources :treatment_plan_notes
   resources :intake_notes
   resources :progress_notes
   resources :to_do_lists
   resources :general_informations
   resources :health_insurances
   resources :family_histories
   resources :emergency_contacts
   resources :immunizations
   resources :diagnoses



   resources :patients

   resources :medications

   resources :allergies


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/allergy.rb
class Allergy < ApplicationRecord
   belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
   belongs_to :patient
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
   belongs_to :patient
end

app/models/family_history.rb
class FamilyHistory < ApplicationRecord
  belongs_to :patient
end

app/models/general_information.rb
class GeneralInformation < ApplicationRecord
   belongs_to :patient
end

app/models/health_insurance.rb
class HealthInsurance < ApplicationRecord
  belongs_to :patient
end

app/models/immunization.rb
class Immunization < ApplicationRecord
  belongs_to :patient
end

app/models/intake_note.rb
class IntakeNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/medication.rb
class Medication < ApplicationRecord
   belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
   belongs_to :user
   has_one :medication
   has_one :allergy
   has_one :general_information
   has_one :immunization
   has_one :health_insurance
   has_one :family_history
   has_one :emergency_contact
   has_one :diagnosis
   has_many :progress_notes
   has_many :intake_notes
   has_many :treatment_plan_notes

   validates :first_name, presence: true
end

app/models/progress_note.rb
class ProgressNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
   has_many :patients
   has_many :to_do_lists

      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  before_action :set_allergy, only: [:show, :edit, :update, :destroy]

  # GET /allergies
  # GET /allergies.json
  def index
    @allergies = Allergy.all
  end

  # GET /allergies/1
  # GET /allergies/1.json
  def show
  end

   # GET /allergies/new
   def new
      @patients=Patient.all
      @allergy = Allergy.new
   end

  # GET /allergies/1/edit
  def edit
     @patients=Patient.all
  end

  # POST /allergies
  # POST /allergies.json
  def create
    @allergy = Allergy.new(allergy_params)

    respond_to do |format|
      if @allergy.save
        format.html { redirect_to patient_path(@allergy.patient), notice: 'Allergy was successfully created.' }
        format.json { render :show, status: :created, location: @allergy }
      else
        format.html { render :new }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allergies/1
  # PATCH/PUT /allergies/1.json
  def update
    respond_to do |format|
      if @allergy.update(allergy_params)
        format.html { redirect_to patient_path(@allergy.patient), notice: 'Allergy was successfully updated.' }
        format.json { render :show, status: :ok, location: @allergy }
      else
        format.html { render :edit }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allergies/1
  # DELETE /allergies/1.json
  def destroy
    @allergy.destroy
    respond_to do |format|
      format.html { redirect_to allergies_url, notice: 'Allergy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allergy
      @allergy = Allergy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allergy_params
      params.require(:allergy).permit(:allergen, :reaction, :severity, :note, :patient_id)
    end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/allergies/_form.html.erb
<%= form_with(model: allergy, local: true) do |form| %>
  <% if allergy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(allergy.errors.count, "error") %> prohibited this allergy from being saved:</h2>

      <ul>
      <% allergy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :allergen %>
    <%= form.text_field :allergen, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :reaction %>
    <%= form.text_field :reaction, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :severity %>
    <%= form.text_field :severity, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :note %>
    <%= form.text_area :note, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :patient_id %>
    <%= form.select('patient_id', options_for_select(@patients.collect{ |p| [ p.first_name, p.id ] }), class:'form-control') %>
  </div>

  <div class="actions">
    <%= form.submit 'Update', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/allergies/edit.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>Editing Allergy</h1>
         <%= render 'form', allergy: @allergy %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/allergies/index.html.erb
<%= render "shared/navbar_signed_in" %>

<p id="notice"><%= notice %></p>

<h1>Allergies</h1>

<table>
  <thead>
    <tr>
      <th>Allergen</th>
      <th>Reaction</th>
      <th>Severity</th>
      <th>Note</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @allergies.each do |allergy| %>
      <tr>
        <td><%= allergy.allergen %></td>
        <td><%= allergy.reaction %></td>
        <td><%= allergy.severity %></td>
        <td><%= allergy.note %></td>
        <td><%= allergy.patient.first_name %></td>
        <td><%= link_to 'Show', allergy %></td>
        <td><%= link_to 'Edit', edit_allergy_path(allergy) %></td>
        <td><%= link_to 'Destroy', allergy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allergy', new_allergy_path %>

<%= render "shared/footer" %>

app/views/allergies/new.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>New Allergy</h1>
         <%= render 'form', allergy: @allergy %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/allergies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Allergen:</strong>
  <%= @allergy.allergen %>
</p>

<p>
  <strong>Reaction:</strong>
  <%= @allergy.reaction %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @allergy.severity %>
</p>

<p>
  <strong>Note:</strong>
  <%= @allergy.note %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @allergy.patient %>
</p>

<%= link_to 'Edit', edit_allergy_path(@allergy) %> |
<%= link_to 'Back', allergies_path %>