config/routes.rb
Rails.application.routes.draw do

   root to: 'application#index'

   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)



   devise_for :users

   resources :users do
      collection do
         get 'show_staff' => 'users#show_staff'
      end
   end

   resources :treatment_plan_notes
   resources :intake_notes
   resources :progress_notes
   resources :to_do_lists
   resources :general_informations
   resources :health_insurances
   resources :family_histories
   resources :emergency_contacts
   resources :immunizations
   resources :diagnoses



   resources :patients

   resources :medications

   resources :allergies


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/allergy.rb
class Allergy < ApplicationRecord
   belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
   belongs_to :patient
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
   belongs_to :patient
end

app/models/family_history.rb
class FamilyHistory < ApplicationRecord
  belongs_to :patient
end

app/models/health_insurance.rb
class HealthInsurance < ApplicationRecord
  belongs_to :patient
end

app/models/immunization.rb
class Immunization < ApplicationRecord
  belongs_to :patient
end

app/models/intake_note.rb
class IntakeNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/medication.rb
class Medication < ApplicationRecord
   belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
   belongs_to :user
   has_one :medication
   has_one :allergy
   has_one :general_information
   has_one :immunization
   has_one :health_insurance
   has_one :family_history
   has_one :emergency_contact
   has_one :diagnosis
   has_many :progress_notes
   has_many :intake_notes
   has_many :treatment_plan_notes

   validates :first_name, presence: true
end

app/models/progress_note.rb
class ProgressNote < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
   has_many :patients
   has_many :to_do_lists

      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

end

app/controllers/health_insurances_controller.rb
class HealthInsurancesController < ApplicationController
  before_action :set_health_insurance, only: [:show, :edit, :update, :destroy]

  # GET /health_insurances
  # GET /health_insurances.json
  def index
    @health_insurances = HealthInsurance.all
  end

  # GET /health_insurances/1
  # GET /health_insurances/1.json
  def show
  end

   # GET /health_insurances/new
   def new
      @patients=Patient.all
      @health_insurance = HealthInsurance.new
   end

   # GET /health_insurances/1/edit
   def edit
      @patients=Patient.all
   end

  # POST /health_insurances
  # POST /health_insurances.json
  def create
    @health_insurance = HealthInsurance.new(health_insurance_params)

    respond_to do |format|
      if @health_insurance.save
        format.html { redirect_to patient_path(@health_insurance.patient), notice: 'Health insurance was successfully created.' }
        format.json { render :show, status: :created, location: @health_insurance }
      else
        format.html { render :new }
        format.json { render json: @health_insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /health_insurances/1
  # PATCH/PUT /health_insurances/1.json
  def update
    respond_to do |format|
      if @health_insurance.update(health_insurance_params)
        format.html { redirect_to patient_path(@health_insurance.patient), notice: 'Health insurance was successfully updated.' }
        format.json { render :show, status: :ok, location: @health_insurance }
      else
        format.html { render :edit }
        format.json { render json: @health_insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_insurances/1
  # DELETE /health_insurances/1.json
  def destroy
    @health_insurance.destroy
    respond_to do |format|
      format.html { redirect_to health_insurances_url, notice: 'Health insurance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_insurance
      @health_insurance = HealthInsurance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def health_insurance_params
      params.require(:health_insurance).permit(:company, :phone, :id_number, :group_number, :coverage, :copays, :patient_id)
    end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/health_insurances_helper.rb
module HealthInsurancesHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/health_insurances/_form.html.erb
<%= form_with(model: health_insurance, local: true) do |form| %>
  <% if health_insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health_insurance.errors.count, "error") %> prohibited this health_insurance from being saved:</h2>

      <ul>
      <% health_insurance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :company %>
    <%= form.text_field :company, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :id_number %>
    <%= form.text_field :id_number, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :group_number %>
    <%= form.text_field :group_number, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :coverage %>
    <%= form.text_field :coverage, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :copays %>
    <%= form.text_field :copays, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :patient_id %>
    <%= form.select('patient_id', options_for_select(@patients.collect{ |p| [ p.first_name, p.id ] }), class:'form-control') %>
  </div>

  <div class="actions">
    <%= form.submit 'Update', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/health_insurances/edit.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>Editing Health Insurance</h1>
         <%= render 'form', health_insurance: @health_insurance %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/health_insurances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Insurances</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Phone</th>
      <th>Id number</th>
      <th>Group number</th>
      <th>Coverage</th>
      <th>Copays</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @health_insurances.each do |health_insurance| %>
      <tr>
        <td><%= health_insurance.company %></td>
        <td><%= health_insurance.phone %></td>
        <td><%= health_insurance.id_number %></td>
        <td><%= health_insurance.group_number %></td>
        <td><%= health_insurance.coverage %></td>
        <td><%= health_insurance.copays %></td>
        <td><%= health_insurance.patient %></td>
        <td><%= link_to 'Show', health_insurance %></td>
        <td><%= link_to 'Edit', edit_health_insurance_path(health_insurance) %></td>
        <td><%= link_to 'Destroy', health_insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health Insurance', new_health_insurance_path %>

app/views/health_insurances/new.html.erb
<%= render "shared/navbar_signed_in" %>

<div class="container py-5">
   <div class="row">
      <div id="blocks" class="col-md-10 mx-auto border py-4">
         <h1>New Health Insurance</h1>
         <%= render 'form', health_insurance: @health_insurance %>
      </div>
   </div>
</div>

<%= render "shared/footer" %>

app/views/health_insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @health_insurance.company %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @health_insurance.phone %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @health_insurance.id_number %>
</p>

<p>
  <strong>Group number:</strong>
  <%= @health_insurance.group_number %>
</p>

<p>
  <strong>Coverage:</strong>
  <%= @health_insurance.coverage %>
</p>

<p>
  <strong>Copays:</strong>
  <%= @health_insurance.copays %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @health_insurance.patient %>
</p>

<%= link_to 'Edit', edit_health_insurance_path(@health_insurance) %> |
<%= link_to 'Back', health_insurances_path %>